### PR TITLE
Fix Unicode support for game names and paths.

### PR DESCRIPTION
**Pull request by LemmusLemmus**
Currently when passing command line arguments, they are always read as UTF-8. This is problematic for paths and game names containing non-UTF-8 characters.

This change should fix that, by replacing `QString::fromStdString` with `QString::fromStdWString`. `toStdWString` is already used when adding/removing targets via the GUI.

For consistency, one might also want to replace `QString::fromStdString` when reading the first argument "remove"/"add".

**Note:** I have not actually built the project to test if this works as expected!

EDIT: `fromStdString` and `toStdString` should possibly be replaced elsewhere as well for UTF-16 chars to work properly across the board.

### CODE REVIEW

**Comment by LemmusLemmus** [comment]
The Shortcuts.vdf Parser and Steam fortunately do not seem to complain about Unicode characters. If the game name contains Unicode characters, one can add it to Steam via the GlosSIConfig GUI. GlosSITarget will not be able to find the `.json` file when you start the shortcut however. I will have to test if Steam and the Shortcuts.vdf parser accept Unicode characters in paths as well.

>Are you willing to take a deeper look at this?

Sure. I'll make sure to actually build and test the solution next time :)

**Comment by LemmusLemmus** [comment]
**Status report:**
So far I have gotten GlosSIConfig to seemingly work with Unicode characters in game names and paths, GlosSITarget remains. I believe one has to use `wmain` for GlosSITarget to read the command line arguments in Unicode (in the case of GlosSIConfig I used `QCoreApplication::arguments().at(n)` to read the command line arguments).

**Comment by Alia5** [comment]
Don't worry about Linux. Theres a whole lot of work to do before that will ever see the light of day.

> I believe one has to use wmain for GlosSITarget to read the command line arguments in Unicode
That's one way.  
Another is
```c++
LPCTSTR pCmdLine = GetCommandLine();
	std::wcout << pCmdLine << L"\n";
```

**Comment by LemmusLemmus** [comment]
This commit should make it possible for various things to contain Unicode characters.

**IMPORTANT NOTE: The commit is incomplete!** I also modified `tweakme.h` in `deps\spdlog\include\spdlog\tweakme.h`, by uncommenting `#define SPDLOG_WCHAR_FILENAMES`. I do not know how to commit it however, since it is in a submodule.

- Linux support is unfortunately borked (at least in main.cpp, GlosSITarget will crash immediately). It should _hopefully_ not be too hard to fix, but I don't know.
- I have probably missed something and I have also possibly change something unnecessarily.
- I have replaced several `std::string` with `std:wstring` (particularly in GlosSITarget). This is not necessarily the best approach. One could for example instead convert `string` to `wstring` only when `wstring` is needed.
- One problem with Unicode on windows remains however: Unicode characters will not be displayed correctly in the overlay log (the log files store them correctly however), instead each Unicode char is replaced by a "?". I do not know how to fix this. Either way, the Roboto font does not support many Unicode characters.
- Aside from string handling, I also changed two other things which are worth mentioning:
	- I removed the constructor parameters from `SteamTarget`, since they were unused and I don't know what to pass to it.
	- I removed the return value from `safeWStringParse`, since, again, it was unused I don't know what to return.

**Comment by LemmusLemmus** [comment]
Instead of modifying `tweakme.h`, I can also simply convert the relevant `wstring` to `string` in `main.cpp` without any difficulty.

**Comment by Alia5** [comment]
>Linux support is unfortunately borked (at least in main.cpp, GlosSITarget will crash immediately). It should hopefully not be too hard to fix, but I don't know.

Don't worry about it, stuff like controller emulation isn't even implemented on Linux and I don't know if it ever will see the light of day ¯\\\_(ツ)_/¯

---

> Instead of modifying tweakme.h, I can also simply convert the relevant wstring to string in main.cpp without any difficulty (if that would be preferred).

Just edit the preprocesser definition in the project file
image

Please do this for **both**, "Release" and "Debug" type builds

---

> One problem with Unicode on Windows remains however: Unicode characters will not be displayed correctly in the overlay 
log (the log files store them correctly however), instead each Unicode char is replaced by a "?". I do not know how to fix this. Either way, the Roboto font does not support many Unicode characters.

A bigger issue than the fonts, actually, is that spdlogs log format only spits out basic strings, not wide strings.   
even though, the logs text file is actually written just fine...  
(spdlogs log format is used in `Overlay::AddLog`)  

after that is solved, we'd have to enable wide char support for ImGui (`#define IMGUI_USE_WCHAR32`)  
but then I have no Idea on how to actually display them, as `ImGui::Text(...)` only accepts basic char arrays...

Ouh well, a little "misprinting" in the displayed log, surely won't hurt anybody, so let's just ignore this for now....

---


Otherwise, this looks fine to me. ;)
After you've added that, I'd gladly merge.

Again, thank you very much for your contribution!

**Comment by LemmusLemmus** [comment]
Done!

**Pull request merged**
